### ISSUE TITLE
Links from section to section are broken

### ISSUE THREAD

**Issue by jimmoores** [jamesroutley/write-a-hash-table#1]
Also links from top level reference directory rather than the .MD file and require an extra click-through.

**Comment by freefal** [comment]
Sent a pull request to fix the links
https://github.com/jamesroutley/write-a-hash-table/pull/2

**Comment by jimmoores** [comment]
Sending a PR is of course what I should have done, thanks.

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jamesroutley** [comment]
Thanks for opening this @jimmoores - @freefal kindly put in a PR fixing the section links. I think I'm going to leave the top level links pointing to the directory rather than the `.md` files themselves. I eventually plan to add full source code at each step, and I think pointing the reader to the directory will make it easier for them to spot the code.

**Comment by jimmoores** [comment]
Thanks!
