### ISSUE TITLE
More info about using prime numbers

### ISSUE THREAD

**Issue by antonmedv** [jamesroutley/write-a-hash-table#11]
Hi,

Nice article. But will be more cool if you can add info about why prime numbers is used?

Why prime?

```
The variable a should be a prime number larger than the size of the alphabet. 
```

Why prime?

```
Our new array size should be a prime number roughly double the current size.
```

Why 0.7 and 0.1?

```
up, if load > 0.7
down, if load < 0.1
```

**Comment by hemangandhi** [comment]
https://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/ suggests that primes are chosen since their products are less likely to occur. I can't come up with convincing number theory or a decent example.

I think `0.7` and `0.1` were found empirically by other people. The Java implementation uses `0.75` as a default, so `0.7` is reasonable. Frankly, I haven't heard of down-sizing a hash table automatically, but it makes sense to in C.

I am sceptical that implementations try to keep the array size prime, though it makes sense: the uniformity of the hashes is higher (using similar number theory I can't come up with as above). That said, it is fairly slow to find a prime, so I don't know if libraries do it.

**Comment by antonmedv** [comment]
And why primes in hash func?

**Comment by hemangandhi** [comment]
That's the first link... https://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/ 

Primes are generally desirable because they don't factor, so it's less likely to get the same product for differing values.

**Comment by jamesroutley** [comment]
Hi all, sorry for the slow response, I've just started a new job and I've been pretty busy this week. 

@antonmedv you're definitely right, the tutorial should have more info on why those numbers should be prime, and where `0.7` and `0.1` came from. I actually started writing a secondary article on why we need the primes, but I got a bit caught up in how to explain the maths well. I've never really taught maths and I wasn't sure what level to pitch it at. 

I think a short term fix might be to link to other articles explaining why primes are needed. I do want to write it up myself at some point though.

@hemangandhi thanks so much for posting those links! It's really great when we help each other out like this!
